server:
  port: 8085

SERVICE_REGISTERY_URL: http://localhost:8761/eureka

spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ashishchoksi/hotel-rating-service-config
          clone-on-start: true

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: ${SERVICE_REGISTERY_URL}